### PR TITLE
Adding in liability and CoC to application

### PR DESCRIPTION
**Pull request by uptonm**
Still need to add in the video waiver per #2

### CODE REVIEW

**Comment by uptonm** [comment]
@corbinhak If we get the video waiver, we can just add it to the hackwitus site through the github repo via a markdown file, also any changes that need to be made to the liability waiver or code of conduct can be made the same way

**Comment by corbinhak** [comment]
@uptonm Right makes sense. In that case I think we should also add a link for the video waiver anyways(at least a placeholder), even though we don't have an official link nor have it ready to upload right now.

**Comment by uptonm** [comment]
Sounds good, I can add that placeholder as soon as I get home 👍
________________________________

**Comment by corbinhak** [comment]
Wait I also just noticed that Liability, CoC, and Photo Release is mentioned in Confirmation.html. Do we want to remove it from there, since we are putting here instead? Or should we keep it there?

**Comment by uptonm** [comment]
I think we should at least leave the links on the initial form as well, just because the confirmation.html file is just for rsvp'ing and adding in additional info. That is where they would put down a digital signature to acknowledge that they accept the waivers

**Pull request closed without merging**
